apiVersion: v1
kind: Service
metadata:
   name: justperform-service
   labels:
      app: justperform
spec:
   type: NodePort
   ports:
   - port: 8080
     nodePort: 30002
     protocol: TCP
   selector:
      app: justperform
